FROM node:20-alpine

WORKDIR /app

# تنظیم رجیستری npm روی یک میرور بدون تحریم برای جلوگیری از خطای شبکه در ایران
RUN npm config set registry https://registry.npmmirror.com/

# اجرای نصب وابستگی‌ها و راه‌اندازی پروژه با npm
CMD sh -c "npm install && npm run dev"