FROM python:3.12-slim

WORKDIR /app

# نصب کتابخانه‌ها
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# اجرای FastAPI با قابلیت رفرش خودکار (--reload)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]